name: riscv-cpu-rv32im
compiler_exe: riscv-none-elf-gcc
objdump_exe: riscv-none-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: riscv-cpu-rv32im.yaml
linker_script: link.ld
dut_include_dir: .
include_priv_tests: False
